name: CI - Logging - Publish
on:  
  workflow_dispatch:
    inputs:
      branch:
        description: name of branch artifact to publish
        default: main
        required: true
        type: string
        
      publishVsix:
        description: Whether to publish the vsix artifact
        default: true
        required: true
        type: boolean
        
      publishNupkg:
        description: Whether to publish the nupkg artifact
        default: true
        required: true
        type: boolean

jobs:
  
  nupkgRunNumber:
    if: ${{ inputs.publishNupkg }}
    uses: ./.github/workflows/get-latest-artifact-run-number.yml
    with:
      gitOwner: ${{ github.repository_owner }}
      gitProject: ${{ github.repository.name }}
      artifactName: "Logging.nupkg"
      branchName: "main"
      
  vsixRunNumber:
    if: ${{ inputs.publishVsix }}
    uses: ./.github/workflows/get-latest-artifact-run-number.yml
    with:
      gitOwner: ${{ github.repository_owner }}
      gitProject: ${{ github.repository.name }}
      artifactName: "Logging.vsix"
      branchName: "main"
      
  vsix:
    if: ${{ inputs.publishNupkg }}
    uses: ./.github/workflows/nupkg-publish.yml
    needs: [nupkgRunNumber]
    with:      
      artifactName: "Logging.nupkg"      
      runNumber: ${{ needs.nupkgRunNumber.outputs.runId }}      
      versionNumber: ''
    secrets:
      nupkgPublishToken: ${{ secrets.NUGET }}  
  
  nupkg:
    if: ${{ inputs.publishVsix }}
    uses: ./.github/workflows/vsix-publish.yml
    needs: [vsixRunNumber]
    with:
      artifactName: "Logging.vsix"
      runNumber: ${{ needs.vsixRunNumber.outputs.runId }}
      vsMarketManifestPath:
      versionNumber: ''
    secrets:
      vsMarketAccessToken: ${{ secrets.VSMARKETACCESSTOKEN }}