name: CI - Logging - Publish
on:  
  workflow_dispatch:

jobs:
  vsix:
    uses: ./.github/workflows/nupkg-publish.yml
    with:
      csprojPath: analyzers/Logging/Logging.Vsix/Logging.Vsix.csproj
      packageSolutionPath: analyzers/Logging/Logging.slnx
      vsixManifestPath: analyzers/Logging/Logging.Vsix/source.extension.vsixmanifest
      artifactName: "Logging.nupkg"
      dotnetVersion: "9.0.x"
  nupkg:
    uses: ./.github/workflows/vsix-publish.yml
    with:
      csprojPath: analyzers/Logging/Logging.Package/Logging.Package.csproj
      packageSolutionPath: analyzers/Logging/Logging.slnx
      artifactName: "Logging.vsix"
      dotnetVersion: "9.0.x"
    secrets:
      vsMarketAccessToken: ${{ secrets.VSMARKETACCESSTOKEN }}
      downloadSecret: ${{ secrets.PATLOCAL }}