name: CI - Logging - Publish
on:  
  workflow_dispatch:
    inputs:
      branch:
        description: name of branch artifact to publish
        default: main
        required: true
        type: string
        
      publishVsix:
        description: Publish Vsix?
        default: true
        required: true
        type: boolean
        
      publishNupkg:
        description: Publish Nupkg?
        default: true
        required: true
        type: boolean

jobs:
  
  nupkgRunNumber:
    if: ${{ inputs.publishNupkg }}
    uses: ./.github/workflows/get-latest-artifact-run-number.yml
    with:
      artifactName: "Logging.nupkg"
      branchName: ${{ inputs.branch }}
      
  vsixRunNumber:
    if: ${{ inputs.publishVsix }}
    uses: ./.github/workflows/get-latest-artifact-run-number.yml
    with:
      artifactName: "Logging.vsix"
      branchName: ${{ inputs.branch }}
      
  nupkg:
    if: ${{ inputs.publishNupkg }}
    uses: ./.github/workflows/publish-nupkg.yml
    needs: [nupkgRunNumber]
    with:      
      artifactName: "Logging.nupkg"      
      runNumber: ${{ needs.nupkgRunNumber.outputs.runId }}      
      versionNumber: ''
    secrets:
      nupkgPublishToken: ${{ secrets.NUGET }}  
  
  vsix:
    if: ${{ inputs.publishVsix }}
    uses: ./.github/workflows/publish-vsix.yml
    needs: [vsixRunNumber]
    with:
      artifactName: "Logging.vsix"
      runNumber: ${{ needs.vsixRunNumber.outputs.runId }}
      vsMarketManifestPath: 'analyzers/Logging/vs-publish.json'
      versionNumber: ''
    secrets:
      vsMarketAccessToken: ${{ secrets.VSMARKETACCESSTOKEN }}