name: CI - Logging - Publish
on:  
  workflow_dispatch:

jobs:
  
  nupkgRunNumber:
    uses: ./.github/workflows/get-latest-artifact-run-number.yml
    with:
      gitOwner: ${{ github.repository_owner }}
      gitProject: ${{ github.repository.name }}
      artifactName: "Logging.nupkg"
      branchName: "main"
      
  vsixRunNumber:
    uses: ./.github/workflows/get-latest-artifact-run-number.yml
    with:
      gitOwner: ${{ github.repository_owner }}
      gitProject: ${{ github.repository.name }}
      artifactName: "Logging.vsix"
      branchName: "main"
      
  vsix:
    uses: ./.github/workflows/nupkg-publish.yml
    needs: [nupkgRunNumber]
    with:      
      artifactName: "Logging.nupkg"      
      runNumber: ${{ needs.nupkgRunNumber.outputs.runId }}      
      versionNumber: ''
    secrets:
      nupkgPublishToken: ${{ secrets.NUGET }}  
  
  nupkg:
    uses: ./.github/workflows/vsix-publish.yml
    needs: [vsixRunNumber]
    with:
      artifactName: "Logging.vsix"
      runNumber: ${{ needs.vsixRunNumber.outputs.runId }}
      vsMarketManifestPath:
      versionNumber: ''
    secrets:
      vsMarketAccessToken: ${{ secrets.VSMARKETACCESSTOKEN }}