name: CI - Logging - Publish
on:  
  workflow_dispatch:

jobs:
  vsix:
    uses: ./.github/workflows/vsix-publish.yml
    with:      
      packageName: Logging
      csprojPath: analyzers/Logging/Logging.Vsix/Logging.Vsix.csproj
      packageSolutionPath: analyzers/Logging/Logging.slnx
      vsixManifestPath: analyzers/Logging/Logging.Vsix/source.extension.vsixmanifest
      vsMarketManifestPath: analyzers/Logging/vs-publish.json
      runPublish: true
      artifactRunNumber: ${{ inputs.runNumber }}
      versionNumber: '' # empty uses the vsix version and only bumps the build number
      dotnetVersion: |
        9.0.x
    secrets:
      vsMarketAccessToken: ${{ secrets.VSMARKETACCESSTOKEN }}
      downloadSecret: ${{ secrets.PATLOCAL }}