name: "GitHub Release"
permissions:
  actions: write
  contents: write

on:
  workflow_call:
    inputs:
      packageName:
        type: string
        description: Name of the analyzer package
        required: true
      
      runPublish:
        type: boolean
        description: Whether to run the publish steps
        required: true
      
      versionNumber:
        type: string
        description: Version for the vsix package
        default: ''
        required: true
        
      nupkgArtifactName:
        type: string
        description: Name of nupkg artifact
        required: true
        
      vsixArtifactName:
        type: string
        description: Name of nupkg artifact
        required: true
jobs:
  release:
    if: ${{ inputs.runPublish }}
    name: release
    runs-on: ubuntu-latest

    steps:

    - name: Download nupkg artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.nupkgArtifactName }}
        path: ${{ github.workspace }}/artifacts
        
    - name: Download vsix artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.vsixArtifactName }}
        path: ${{ github.workspace }}/artifacts
      
    - name: Tag and release
      id: tag_release
      uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
      with:
        body: release ${{ inputs.versionNumber }}
        generate_release_notes: true
        tag_name: v${{ inputs.versionNumber }}
        files: |
          ${{github.workspace}}/artifacts/**/*.*