name: "VSIX Release"
permissions:
  actions: write
  contents: write

on:
  workflow_call:
    inputs:
        
      artifactName:
        type: string
        description: Path to the .slnx
        required: true
      
      runNumber:
        type: number
        description: Run number of artifact
        required: true
        
      vsMarketManifestPath:
        type: string
        description: Path to the vs-publish.json
        required: true
        
      versionNumber:
        type: string
        description: Version for the vsix package
        default: ''
        required: false
        
    secrets:      
      vsMarketAccessToken:
        description: VS Market secret
        required: true
        
jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Download Package artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifactName }}
          path: ${{github.workspace}}/artifacts
          
      - name: get artifacts vsix path
        id: vsixPath
        shell: pwsh
        run: |
          $path = Get-ChildItem -Path "${{github.workspace}}/artifacts" -Filter "*.vsix" | Select-Object -ExpandProperty FullName -First 1
          echo "result=$path" >> $env:GITHUB_OUTPUT

      - name: Upload to Open VSIX
        uses: timheuer/openvsixpublish@04b38d641d8b7475ab6ddece48e42525d58b0875
        with:
          vsix-file: '${{ steps.vsixPath.outputs.result }}'

      - name: Publish extension to Marketplace
        if: ${{ env.ACCESSTOKEN != '' }}
        uses: cezarypiatek/VsixPublisherAction@d28bc8109d6eaa67fa28e611d5b4557e90683bdd
        with:
          extension-file: '${{ steps.vsixPath.outputs.result }}'
          publish-manifest-file: ${{ inputs.vsMarketManifestPath }}
          personal-access-code: ${{ secrets.vsMarketAccessToken }}
        env: 
          ACCESSTOKEN: ${{ secrets.vsMarketAccessToken }}