name: "VSIX Download Artifact & Release"
permissions:
  actions: write
  contents: write

on:
  workflow_call:
    inputs:
      packageName:
        type: string
        description: Name of the analyzer package
        required: true
        
      csprojPath:
        type: string
        description: Path to the .csproj
        required: true
        
      packageSolutionPath:
        type: string
        description: Path to the .slnx
        required: true
        
      vsixManifestPath:
        type: string
        description: Path to the .vsixmanifest
        required: true
        
      vsMarketManifestPath:
        type: string
        description: Path to the vs-publish.json
        required: true
        
      runPublish:
        type: boolean
        description: Whether to run the publish steps
        required: true
        
      versionNumber:
        type: string
        description: Version for the vsix package
        default: ''
        required: false
        
      dotnetVersion:
        type: string
        description: dotnet versions of the workflow
        default: "9.0.0"
        required: false
      
      artifactRunNumber:
        type: string
        description: Run number to download the artifact
        required: true
    
    secrets:      
      vsMarketAccessToken:
        description: VS Market secret
        required: true
        
jobs:

  publish:
    if: ${{ inputs.runPublish }}
    runs-on: windows-latest
    env: 
      ACCESSTOKEN: ${{ secrets.vsMarketAccessToken }}

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.packageName }}.vsix
          github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
          repository: taori/S4u.Analyzers
          run-id: 14896117076

      - name: Download via CURL
        shell: pwsh
        run: |
          mkdir /download
          $url = "https://api.github.com/repos/taori/S4u.Analyzers/actions/artifacts"
          $response = Invoke-RestMethod -Uri $url -Headers @{ "User-Agent" = "PowerShellScript" }
          $filtered = $response.artifacts | Where-Object {
            $_.name -eq "Logging.vsix" -and $_.workflow_run.head_branch -eq "main"
          }
          $latest = $filtered | Sort-Object -Property created_at -Descending | Select-Object -First 1
          #$latest | Format-List
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o /download/download.zip "$($latest.archive_download_url)"
          
          Expand-Archive -Path "/download/download.zip" -DestinationPath "/unzipped" -Force

      - name: Upload to Open VSIX
        uses: timheuer/openvsixpublish@04b38d641d8b7475ab6ddece48e42525d58b0875
        with:
          vsix-file: '/unzipped/${{ inputs.packageName }}.vsix'

      - name: Publish extension to Marketplace
        if: ${{ env.ACCESSTOKEN != '' }}
        uses: cezarypiatek/VsixPublisherAction@d28bc8109d6eaa67fa28e611d5b4557e90683bdd
        with:
          extension-file: '/unzipped/${{ inputs.packageName }}.vsix'
          publish-manifest-file: ${{ inputs.vsMarketManifestPath }}
          personal-access-code: ${{ secrets.vsMarketAccessToken }}

#      - name: Tag and release
#        id: tag_release
#        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
#        with:
#          body: release ${{ needs.build.outputs.version }}
#          generate_release_notes: true
#          tag_name: ${{ needs.build.outputs.version }}
#          files: |
#            **/*.vsix